import cv2 as cv
import numpy as np
import numpy.typing as npt

from time import struct_time


def generate_clock_image(time: struct_time) -> npt.NDArray[np.int_]:
    """
    Generate a JPEG image of an analog clock
    showing the given time.

    :param time: The time the clock in the generated image will show.
    :return: The image, as a numpy array.
    """
    pass


def read_the_time(img: npt.NDArray[np.int_]) -> struct_time:
    """
    Receives an image generated by generate_clock_image and returns the time
    shown by the clock.

    :param img: The image that was generated by generate_clock_image.
    :return: The time clock in the image was displaying
    """
    pass
